<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>cfg</string>
    </array>
    <key>name</key>
    <string>Pynsist Configuration</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.pynsist</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*(;|#).*$\n?</string>
            <key>name</key>
            <string>comment.line.semicolon.pynsist</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\$(ADMINTOOLS|APPDATA|CDBURN_AREA|COMMONFILES|COOKIES|DESKTOP|DOCUMENTS|EXEDIR|FAVORITES|FONTS|HISTORY|INSTDIR|INTERNET_CACHE|LOCALAPPDATA|MUSIC|NETHOOD|OUTDIR|PICTURES|PLUGINSDIR|PRINTHOOD|PROFILE|PROGRAMFILES(32|64)?|QUICKLAUNCH|RECENT|RESOURCES_LOCALIZED|RESOURCES|SENDTO|SMPROGRAMS|SMSTARTUP|STARTMENU|SYSDIR|TEMP|TEMPLATES|VIDEOS|WINDIR)</string>
            <key>name</key>
            <string>variable.language.pynsist</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\$(\{PRODUCT_NAME\})</string>
            <key>name</key>
            <string>constant.language.pynsist</string>
        </dict>
        <dict>
            <key>match</key>
            <string>((0(x|X)[0-9a-fA-F]{3,6})|([0-9]+(\.[0-9]+)*))\b</string>
            <key>name</key>
            <string>constant.numeric.pynsist</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.section.pynsist</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.section.pynsist</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.section.pynsist</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*(\[)(.*?)(\])</string>
            <key>name</key>
            <string>entity.name.section.nsis</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.property.pynsist</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.quote.pynsist</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>keyword.name.pynsist</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.quote.pynsist</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.equals.pynsist</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>meta.value.pynsist</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.quote.pynsist</string>
                </dict>
                <key>8</key>
                <dict>
                    <key>name</key>
                    <string>string.name.value.pynsist</string>
                </dict>
                <key>9</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.quote.pynsist</string>
                </dict>
                <key>10</key>
                <dict>
                    <key>name</key>
                    <string>comment.declarationline.semicolon.pynsist</string>
                </dict>
                <key>11</key>
                <dict>
                    <key>name</key>
                    <string>variable.language.pynsist</string>
                </dict>
                <key>12</key>
                <dict>
                    <key>name</key>
                    <string>constant.language.pynsist</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(\s*(["'']?)(.+?)(\2)\s*(=))?\n?</string>
            <key>name</key>
            <string>meta.declaration.pynsist</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.pynsist</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.pynsist</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.pynsist</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(?i)\$(ADMINTOOLS|APPDATA|CDBURN_AREA|COMMONFILES|COOKIES|DESKTOP|DOCUMENTS|EXEDIR|FAVORITES|FONTS|HISTORY|INSTDIR|INTERNET_CACHE|LOCALAPPDATA|MUSIC|NETHOOD|OUTDIR|PICTURES|PLUGINSDIR|PRINTHOOD|PROFILE|PROGRAMFILES(32|64)?|QUICKLAUNCH|RECENT|RESOURCES_LOCALIZED|RESOURCES|SENDTO|SMPROGRAMS|SMSTARTUP|STARTMENU|SYSDIR|TEMP|TEMPLATES|VIDEOS|WINDIR)</string>
                    <key>name</key>
                    <string>variable.other.pynsist</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?i)\$(\{PRODUCT_NAME\})</string>
                    <key>name</key>
                    <string>constant.language.pynsist</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.pynsist</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.pynsist</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.pynsist</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(?i)\$(ADMINTOOLS|APPDATA|CDBURN_AREA|COMMONFILES|COOKIES|DESKTOP|DOCUMENTS|EXEDIR|FAVORITES|FONTS|HISTORY|INSTDIR|INTERNET_CACHE|LOCALAPPDATA|MUSIC|NETHOOD|OUTDIR|PICTURES|PLUGINSDIR|PRINTHOOD|PROFILE|PROGRAMFILES(32|64)?|QUICKLAUNCH|RECENT|RESOURCES_LOCALIZED|RESOURCES|SENDTO|SMPROGRAMS|SMSTARTUP|STARTMENU|SYSDIR|TEMP|TEMPLATES|VIDEOS|WINDIR)</string>
                    <key>name</key>
                    <string>variable.other.pynsist</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?i)\$(\{PRODUCT_NAME\})</string>
                    <key>name</key>
                    <string>constant.language.pynsist</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.cfg.pynsist</string>
    <key>uuid</key>
    <string>61042DD3-D2AF-4DF2-9FDE-266975DFEDE6</string>
</dict>
</plist>
