<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>installer.cfg</string>
	</array>
	<key>name</key>
	<string>Pynsist Configuration</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ini</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ini.pynsist</string>
	<key>uuid</key>
	<string>e681b761-41da-4c79-a69b-04f6790f9517</string>
</dict>
</plist>